name: 'Yarn install'
description: 'Installs dependencies with yarn (including private dependencies)'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: 16.13.0
  auth-token:
    description: 'GitHub authentication token'
    required: false 
    default: ''
  install-command:
    description: 'Command to install the project'
    required: false
    default: yarn
  cache:
    description: 'What to cache'
    required: false
    default: 'yarn'
  npmrc-paths: 
    description: 'Relative paths to where npmrc files should be placed'
    required: false
    default: ''
runs:
  using: composite 
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: https://registry.npmjs.org/

    - name: Copy .npmrc
      if: ${{ inputs.npmrc-paths }} != ''
      shell: bash
      run: |
        createNpmrc() {
          echo "//registry.npmjs.org/:_authToken=${{ inputs.auth-token }}" > $1/.npmrc
        }
        echo ${{ inputs.npmrc-paths }} | xargs -n1 createNpmrc
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}

    - run: ${{ inputs.install-command }}
      shell: bash  
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}