name: 'Yarn install'
description: 'Installs dependencies with yarn (including private dependencies)'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: 16.13.0
  auth-token:
    description: 'GitHub authentication token'
    required: false
    default: ''
  marmelab-token:
    description: 'Auth token for marmelab registry (react-admin)'
    required: false
    default: ''
  install-command:
    description: 'Command to install the project'
    required: false
    default: yarn --frozen-lockfile
  cache:
    description: 'What to cache'
    required: false
    default: 'yarn'
  npmrc-paths:
    description: 'Relative paths to where npmrc files should be placed'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: https://registry.npmjs.org/

    - name: Copy .npmrc
      if: ${{ inputs.npmrc-paths }} != ''
      shell: bash
      run: echo ${{ inputs.npmrc-paths }} | xargs -I{} sh -c 'echo "//registry.npmjs.org/:_authToken=${{ inputs.auth-token }}" > $1/.npmrc' -- {}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}

    - name: Add marmelab token to .npmrc
      if: ${{ inputs.npmrc-paths }} != '' && ${{ inputs.marmelab-token }} != ''
      shell: bash
      run: echo ${{ inputs.npmrc-paths }} | xargs -I{} sh -c 'echo "@react-admin:registry=https://registry.marmelab.com\n//registry.marmelab.com/:_authToken=${{ inputs.marmelab-token }}" >> $1/.npmrc' -- {}

    - run: ${{ inputs.install-command }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}
