name: 'Yarn install'
description: 'Installs dependencies with yarn (including private dependencies)'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: 16.13.0
  auth-token:
    description: 'GitHub authentication token'
    required: false 
    default: ''
  install-command:
    description: 'Command to install the project'
    required: false
    default: 'yarn'
  cache:
    description: 'What to cache'
    required: false
    default: 'yarn'
runs:
  using: composite 
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: https://registry.npmjs.org/
        
    - run: ${{ inputs.install-command }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}