name: Bump version
on:
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: askeladdenco/actions/auto-tag@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
